version: '3.3'
services:
  foodify:
    container_name: ${PROJECT_NAME}
    hostname: foodify
    restart: always
    image: ${PROJECT_NAME}_image
    devices:
      - /dev/video0:/dev/video0
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./foodify:/foodify/
      - vol_logs_foodify:/foodify/logs
    env_file:
      - .env
    ports:
      - "${FASTAPI_PORT}:${FASTAPI_PORT}"
    logging:
      driver: "json-file"
      options:
        max-size: 50m
        max-file: "2"

  postgres:
    image: postgres:14
    container_name: ${PROJECT_NAME}_postgres
    hostname: postgres
    restart: 'always'
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: 50m
        max-file: "2"
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"
    volumes:
      - vol_foodify_postgres_db:/var/lib/postgresql/data
    depends_on:
      - foodify

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ${PROJECT_NAME}_pgadmin
    restart: always
    env_file:
      - .env
    ports:
      - "5050:5050"
    volumes:
      - vol_foodify_pgadmin_data:/var/lib/pgadmin

volumes:
  vol_logs_foodify:
    driver: local
  vol_foodify_postgres_db:
    driver: local
  vol_foodify_pgadmin_data:
    driver: local